{
  "full_name":        "Your legal name as it appears on government-issued ID. Used to issue the policy document.",
  "dob":              "Your date of birth determines your age bracket, which affects premium calculation.",
  "age":              "Age is a primary risk factor — premiums and coverage limits vary by age group.",
  "gender":           "Gender influences actuarial risk tables used to calculate life insurance premiums.",
  "marital_status":   "Marital status can affect nominee preferences and certain policy benefits.",
  "phone":            "Required for OTP verification, policy alerts, and claim communication.",
  "email":            "Policy documents and renewal reminders are sent to this email address.",
  "address":          "Your residential address is printed on the policy and used for KYC compliance.",
  "city":             "City information helps determine regional risk factors and applicable state taxes.",
  "pincode":          "PIN code is required for address verification and local office assignment.",
  "aadhaar":          "Aadhaar is mandatory for KYC (Know Your Customer) as per IRDAI regulations.",
  "pan":              "PAN is required for policies with annual premium above ₹50,000 as per Income Tax rules.",
  "occupation":       "Your occupation determines occupational hazard risk, which affects premium rates.",
  "employer":         "Employer details are used for group insurance tie-ups and income verification.",
  "annual_income":    "Annual income is used to determine the maximum coverage amount you are eligible for (typically 10-20x income).",
  "height":           "Height is used along with weight to calculate BMI, a key health risk indicator.",
  "weight":           "Weight combined with height gives BMI, which affects health and life insurance eligibility.",
  "smoking_status":   "Smokers face higher health risks; this directly impacts premiums (typically 1.5-2x higher).",
  "pre_existing":     "Pre-existing conditions affect coverage terms, waiting periods, and premium loading.",
  "nominee_name":     "The nominee is the person who will receive the claim amount in the event of the policyholder's death.",
  "nominee_relation": "Relationship to the nominee is required for legal validity of the nomination.",
  "nominee_dob":      "Nominee's date of birth is required if the nominee is a minor, to appoint a guardian.",
  "policy_type":      "The type of insurance (Term, Health, ULIP, etc.) determines coverage structure and benefits.",
  "coverage_amount":  "The sum assured — the amount paid out on a claim. Must be within eligibility limits.",
  "policy_term":      "The duration of the policy affects total premium outflow and coverage period."
}
